### PR TITLE
Fix GetUplinkRepresentor - Detecting incorrect Uplink Representor

### LINKED ISSUE #32: Missing comparsion for detecting uplink rep
Cited code [1] missed to detect uplink rep netdev correctly.
It doesn't read the physical port name to prove that if its uplink rep or not. (p0/p1) etc.

Hence fix it to do
(a) Use devlink port APIs (once its available)
until than,
(b) Read the phys_port_name; compare it with p0,p1,p2,p3.
If (b) fails on older kernel,
default to current way to find out if its uplink or not.

(b) and (c) is still needed as this code may run on kernel that may not have the devlink output.

[1] https://github.com/Mellanox/sriovnet/blob/4bbe16c3b7c65c44cb1d749b374679b076bb3469/sriovnet_switchdev.go#L60

### PR DESCRIPTION
**Pull request by Mmduh-483**
GetUplinkRepresentor return wrong uplink representor name when it's not preceding the Vfs representors alphabetical.

Fixes #32

### CODE REVIEW

**Comment by Mmduh-483** [comment]
@adrianchiris

File: sriovnet_switchdev.go [hunk 1]
```diff
@@ -65,6 +65,13 @@ func GetUplinkRepresentor(vfPciAddress string) (string, error) {
 	}
 	for _, device := range devices {
 		if isSwitchdev(device.Name()) {
+			// Try to get the phys port name, if not exists then fallback to check without it
```
Comment (adrianchiris) [inline sriovnet_switchdev.go:68]: can you explain the the comment that uplink representor phys port name is expected to be in the format of `p<port-num>` e.g `p0`

**Comment by adrianchiris** [comment]
can you extend unit tests with additional to cover the new flow for vf/pf representor for both good and bad flow cases ?

**Comment by adrianchiris** [comment]
@Mmduh-483 Can you add more info in the commit message ?
Today this code works but recent kernel change will break current code logic

so lets explain this properly in the commit message including a link to the kernel change, some explanation about how the kernel change affects userspace and this code and the way you propose to support it

File: sriovnet_switchdev_test.go [hunk 2]
```diff
@@ -11,49 +11,114 @@ import (
...
+	return nil
+}
+
 //nolint:unparam
-func setupUplinkRepresentorEnv(t *testing.T, vfPciAddress string) func() {
+func setupUplinkRepresentorEnv(t *testing.T, uplink *repContext, vfPciAddress string, vfReps []*repContext) func() {
 	var err error
 	utilfs.Fs = utilfs.NewFakeFs()
-	path := filepath.Join(PciSysDir, vfPciAddress, "physfn/net", "eth0")
+	path := filepath.Join(PciSysDir, vfPciAddress, "physfn/net")
```
Comment (adrianchiris) [inline sriovnet_switchdev_test.go:58]: i see you call this in L#21, do you need it here as well ?

File: sriovnet_switchdev_test.go [hunk 3]
```diff
@@ -83,9 +151,7 @@ func TestGetUplinkRepresentorErrorEmptySwID(t *testing.T) {
 func TestGetUplinkRepresentorErrorMissingUplink(t *testing.T) {
 	var testErr error
 	vfPciAddress := "0000:03:00.4"
-	teardown := setupUplinkRepresentorEnv(t, vfPciAddress)
 	expectedError := fmt.Sprintf("failed to lookup %s", vfPciAddress)
-	defer teardown()
 	path := filepath.Join(PciSysDir, vfPciAddress)
 	testErr = utilfs.Fs.RemoveAll(path)
```
Comment (adrianchiris) [inline sriovnet_switchdev_test.go:156]: I think this should be removed as well together with the defer below
as we are not creating anything, so no need to delete paths

File: sriovnet_switchdev_test.go [hunk 4]
```diff
@@ -63,8 +128,11 @@ func TestGetUplinkRepresentorErrorMissingSwID(t *testing.T) {
 func TestGetUplinkRepresentorErrorEmptySwID(t *testing.T) {
 	var testErr error
 	vfPciAddress := "0000:03:00.4"
+	uplinkRep := &repContext{"eth0", "p0", ""}
+	vfsReps := []*repContext{{"enp_0", "pf0vf0", "0"},
```
Comment (adrianchiris) [inline sriovnet_switchdev_test.go:132]: if switch ID is empty we dont expect to have other representors so i think vfsReps should be empty

File: sriovnet_switchdev_test.go [hunk 5]
```diff
@@ -63,8 +128,11 @@ func TestGetUplinkRepresentorErrorMissingSwID(t *testing.T) {
 func TestGetUplinkRepresentorErrorEmptySwID(t *testing.T) {
 	var testErr error
 	vfPciAddress := "0000:03:00.4"
+	uplinkRep := &repContext{"eth0", "p0", ""}
```
Comment (adrianchiris) [inline sriovnet_switchdev_test.go:131]: if switch ID is empty we dont expect to have `phys_port_name` for uplink so perhaps set it to ""

File: sriovnet_switchdev_test.go [hunk 6]
```diff
@@ -11,49 +11,114 @@ import (
...
+	err = setUpRepresentorLayout(vfPciAddress, uplink)
+	for _, rep := range vfReps {
+		err = setUpRepresentorLayout(vfPciAddress, rep)
+	}
+
 	return func() { utilfs.Fs.RemoveAll("/") } //nolint:errcheck
 }
 
-func TestGetUplinkRepresentorSuccess(t *testing.T) {
+func TestGetUplinkRepresentorWithPhysPortNameSuccess(t *testing.T) {
```
Comment (adrianchiris) [inline sriovnet_switchdev_test.go:74]: Can we have a test case for a single uplink rep without vfReps ? 
i know its covered by this method but it would help clarify that there are two possible scenarios here

1. with single uplink rep under PF
2. with uplink rep and vf reps under PF

**Review by adrianchiris — CHANGES_REQUESTED** [review]

File: sriovnet_switchdev_test.go (hunk 2 above)
Comment (Mmduh-483) [reply sriovnet_switchdev_test.go:58]: It is not needed, removed

File: sriovnet_switchdev_test.go (hunk 3 above)
Comment (Mmduh-483) [reply sriovnet_switchdev_test.go:156]: removed

File: sriovnet_switchdev_test.go (hunk 4 above)
Comment (Mmduh-483) [reply sriovnet_switchdev_test.go:132]: changed

File: sriovnet_switchdev_test.go (hunk 5 above)
Comment (Mmduh-483) [reply sriovnet_switchdev_test.go:131]: changed

File: sriovnet_switchdev_test.go (hunk 6 above)
Comment (Mmduh-483) [reply sriovnet_switchdev_test.go:74]: It is covered in the flowing function `TestGetUplinkRepresentorWithoutPhysPortNameSuccess`

**Review by adrianchiris — APPROVED** [review]
